"""ammount added to transactions

Revision ID: 9a1044c5544f
Revises: ffa218b06455
Create Date: 2022-04-09 16:31:55.079110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1044c5544f'
down_revision = 'ffa218b06455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transaction', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transaction', 'amount')
    # ### end Alembic commands ###
